<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LocalGateway.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.60.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalGateway.Features\LocalGateway.Features.csproj" />
    <ProjectReference Include="..\..\Shared\Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Protos\Shared.Protos.csproj" />
    <ProjectReference Include="..\..\Shared\Utils\Shared.Utils.csproj" />
  </ItemGroup>

</Project>
