<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AspireComponentGroup>AppHost</AspireComponentGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIOrchestrator\AIOrchestrator.Service\AIOrchestrator.Service.csproj" IsAspireProjectResource="true" />
    <ProjectReference Include="..\BffGateway\BffGateway.Service\BffGateway.Service.csproj" IsAspireProjectResource="true" />
    <ProjectReference Include="..\CoreBackend\CoreBackend.Service\CoreBackend.Service.csproj" IsAspireProjectResource="true" />
    <ProjectReference Include="..\Jobs\Jobs.Service\Jobs.Service.csproj" IsAspireProjectResource="true" />
    <ProjectReference Include="..\LocalGateway\LocalGateway.Service\LocalGateway.Service.csproj" IsAspireProjectResource="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.2.2" />
  </ItemGroup>

</Project>
