<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RulesEngine.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RulesEngine.Features\RulesEngine.Features.csproj" />
  </ItemGroup>

</Project>
