<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.25.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.60.0" />
    <PackageReference Include="Grpc.Tools" Version="2.60.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\proto\core\*.proto" GrpcServices="Both" ProtoRoot="..\..\..\proto" />
  </ItemGroup>

</Project>
