<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CoreBackend.Features</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreBackend.Domain\CoreBackend.Domain.csproj" />
    <ProjectReference Include="..\..\VerticalSliceArchitecture.Core\VerticalSliceArchitecture.Core.csproj" />
    <ProjectReference Include="..\..\VerticalSliceArchitecture.Analyzers\VerticalSliceArchitecture.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
