name: Deploy Dispatcher

on:
  push:
    branches:
      - main        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: tailscale configure kubeconfig text-rpg-cluster
